### ISSUE TITLE
Add Salvage Logging to Base Harvest?

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extensions-Disturbance#2]
Reported by lbross@pdx.edu, Oct 22, 2014
From Caren Dymond: I was wondering if you would be willing to add a sort type parameter for standing snag biomass. This would allow simulation of salvage harvesting - a big deal in the west with the pine beetle epidemic and in the boreal with forest fires.

I can share the ForCS code so you can see which pool in the site cohorts would need to be used for sorting.

**Comment by lbross** [comment]
Closing issue. It was moved to issue 1 in Extension-Base-Harvest repo
